version: "3"

services:
  web:
    container_name: web
    image: jihwooon/devops-platform-frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    image: jihwooon/devops-platform-backend
    restart: always
    ports:
      - 3031:3031
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
