version: "3"

services:
  web:
    container_name: devops-platform-web
    image: jihwooon/devops-platform-frontend
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: devops-platform-api
    image: jihwooon/devops-platform-backend
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3031:3031
    env_file:
      - ./apps/api/.env.prod
    environment:
      - NODE_ENV=prod
    networks:
      - app_network
  swagger:
    container_name: devops-platform-openapi
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    restart: always
    environment:
      - URLS_PRIMARY_NAME=agenta
      - "URLS=[{ url: 'docs/openapi.yaml', name: 'agent' }]"
      - SUPPORTED_SUBMIT_METHODS=['get']
    volumes:
      - ./docs:/usr/share/nginx/html/docs

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
