openapi: 3.0.3
info:
  title: DevOps-Platform API
  version: 1.0.0
servers:
  - url: http://localhost:3031
paths:
  /health:
    get:
      description: Get a health check
      responses:
        200:
          description: OK
  /git/login:
    get:
      description: Get a login
      responses:
        200:
          description: Git login
  /git/repo:
    get:
      description: Get a repo Name
      parameters:
        - name: repo_name
          in: query
          required: true
          schema:
            type: string
          description: The name of the repo
      responses:
        200:
          description: Git repp Name
  /git/repo/{repo_name}/issues/{issue_number}:
    get:
      description: Get a repo issue
      parameters:
        - name: repo_name
          in: path
          required: true
          schema:
            type: string
          description: The name of the repo
        - name: issue_number
          in: path
          required: true
          schema:
            type: integer
          description: The issue number
      responses:
        200:
          description: Git repo issue
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  body:
                    type: string
