name: devops-plateform-frontend

on:
  push:
    branches:
      - "develop/**"
      - "release/**"
    paths:
      - "apps/web/**"

env:
  NAME: ${{secrets.DOCKERHUB_USERNAME}}
  REPO: devops-platform-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build with pnpm
        run: pnpm build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{env.NAME}}/${{env.REPO}}:latest
